In [1]:
import numpy as np


In [6]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [7]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
a.ndim

1

In [12]:
b.ndim

2

In [13]:
a.shape

(4,)

In [14]:
b.shape

(2, 5)

In [15]:
a.dtype

dtype('int32')

In [16]:
b.dtype

dtype('int32')

In [17]:
a.itemsize

4

In [18]:
b.itemsize

4

In [19]:
# accesssing and changinging specific row and coloumns

In [20]:
aa=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
aa

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [26]:
aa[0,3]

4

In [28]:
aa[0,-3] # or we can write

4

In [29]:
aa[0,:] #find specific row

array([1, 2, 3, 4, 5, 6])

In [30]:
aa[1,:]

array([ 7,  8,  9, 10, 11, 12])

In [31]:
# find specific coloumns

In [32]:
aa[:,1]

array([2, 8])

In [33]:
aa[:,0]

array([1, 7])

In [34]:
aa[::,4]

array([ 5, 11])

In [38]:
aa[0,1:-1:2]

array([2, 4])

In [46]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [53]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [54]:
np.full_like((2,2),99)

array([99, 99])

In [56]:
np.random.random_sample(4)

array([0.39933554, 0.04911226, 0.88285127, 0.75241216])

In [57]:
np.random.rand(4,2)

array([[0.90196645, 0.87637883],
       [0.89291257, 0.77054915],
       [0.24746401, 0.26198387],
       [0.12941135, 0.33034435]])

In [63]:
np.random.randint(40,48,size=(3,3))

array([[40, 42, 43],
       [45, 44, 46],
       [45, 40, 47]])

In [71]:
arr=np.array([1,2,3])
r1=np.repeat(arr,3,axis=0)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [76]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
r2=np.repeat(arr,3,axis=0)
r2

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [81]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [82]:
a+2

array([3, 4, 5, 6])

In [83]:
a*2

array([2, 4, 6, 8])

In [84]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [85]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [86]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [95]:
aa=np.ones((3,2))
bb=np.full((3,2),2)
print(aa)
print(bb)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [97]:
np.min(aa)

1.0

In [98]:
np.max(bb)

2