In [1]:
import math.pi
pi

ModuleNotFoundError: No module named 'math.pi'; 'math' is not a package

In [2]:
import math
math.pi
pi

NameError: name 'pi' is not defined

# NUMPY MODULE

In [3]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [6]:
a.dtype(a)

TypeError: 'numpy.dtype' object is not callable

In [9]:
a = np.array([1, 2, 3],[6,4,5])
a.dtype

TypeError: data type not understood

In [11]:
import numpy as np
a= np.array([[2,3,4],[5,6,7]])
a

array([[2, 3, 4],
       [5, 6, 7]])

In [12]:
a.dtype

dtype('int32')

In [13]:
a.itemsize

4

In [14]:
a.shape

(2, 3)

In [15]:
a.data

In [16]:
a.ndim

2

In [17]:
a = np.array([['a', 'b'],['c', 'd']])
a

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [18]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
#from numpy import eye
np.identity(100,dtype=int)

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [30]:
a=10;
b=20;
print(a+b);

30


In [39]:
b=np.array[1,2]
c=np.array[2,3]
b+c


TypeError: 'builtin_function_or_method' object is not subscriptable

In [37]:
a=np.arange(4)
b=np.arange(4,8)
a+b

array([ 4,  6,  8, 10])

In [38]:
a=np.arange(4)

In [40]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [41]:
np.dot(A,B)

NameError: name 'A' is not defined

In [4]:
import numpy as np
np.zeros((2,3))
np.ones((4,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [21]:
a=np.ones((5,5))
a
b=np.zeros((3,3))
b[1,1]=5
b
a[1:4,1:4]=b
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 5., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
a=np.ones((5,5))
a
b=np.zeros((3,3))
b[2,1]=3
b
a[1:4,1:4]=b
a


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 3., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.full_like((2,2),99)

array([99, 99])

In [52]:
np.full((4,3),4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [30]:
np.full_like(2,4)

array(4)

In [31]:
np.random.rand(4,2)

array([[0.17401135, 0.02670043],
       [0.72786786, 0.04523228],
       [0.81083058, 0.87852713],
       [0.08326693, 0.00233355]])

In [33]:
np.random.random(a.shape)

array([[0.46788906, 0.43897681, 0.51003798, 0.76854421, 0.67624078],
       [0.87305641, 0.99805534, 0.69412317, 0.96328764, 0.25009855],
       [0.36087391, 0.9722281 , 0.06224923, 0.06239344, 0.53359273],
       [0.69962554, 0.59030069, 0.42013786, 0.72165291, 0.51028858],
       [0.62312029, 0.60981816, 0.38858357, 0.21434512, 0.82237166]])

In [34]:
np.random.randint(4,8,size=(3,3))

array([[7, 4, 5],
       [7, 5, 5],
       [6, 6, 7]])

In [44]:
np.random.randint(4,8,size=(3,3,4))

array([[[5, 4, 7, 6],
        [6, 5, 7, 4],
        [4, 5, 6, 4]],

       [[4, 7, 5, 4],
        [4, 6, 4, 4],
        [7, 4, 5, 6]],

       [[7, 7, 7, 6],
        [6, 4, 5, 5],
        [5, 5, 6, 6]]])

In [45]:
np.identity

<function numpy.identity(n, dtype=None)>

In [46]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
r=np.repeat(a,4,axis=0)
r

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 3., 0., 1.],
       [1., 0., 3., 0., 1.],
       [1., 0., 3., 0., 1.],
       [1., 0., 3., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
b=np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [55]:
a=np.ones((4,4))
a
b=np.full((2,2),5)
b
a[1:3,1:3]=b
a


array([[1., 1., 1., 1.],
       [1., 5., 5., 1.],
       [1., 5., 5., 1.],
       [1., 1., 1., 1.]])

In [56]:
np.cos(a)

array([[0.54030231, 0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.28366219, 0.28366219, 0.54030231],
       [0.54030231, 0.28366219, 0.28366219, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231, 0.54030231]])

In [57]:
np.sin(b)

array([[-0.95892427, -0.95892427],
       [-0.95892427, -0.95892427]])

In [65]:
x=np.array([1,3,5])
y=np.array([7,9,11])
c=np.matmul(x,y)
c

89

In [63]:
c=np.identity(3)
np.linalg.det(c)

1.0

In [64]:
np.linalg.det(a)

0.0

In [67]:
s=np.array([[1,2,3],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.min(s)

1

In [69]:
np.max(a)

5.0

In [70]:
np.max(s)

6

In [71]:
np.sum(s)

21

In [75]:
np.inverse(s)

AttributeError: module 'numpy' has no attribute 'inverse'

In [76]:
np.linalg.inv(s)

LinAlgError: Last 2 dimensions of the array must be square

In [79]:
c=np.linalg.inv(s)
c

LinAlgError: Last 2 dimensions of the array must be square

In [81]:
from numpy.linalg import inv
d=np.linalg.inv(s)
d

LinAlgError: Last 2 dimensions of the array must be square

In [89]:
e=s.reshape((6,1))

NameError: name 'VJVNJ' is not defined

# PANDA MODULE

In [91]:
import pandas as pd
data=[1,2,3,4,5]
s=pd.Series(data)
s


0    1
1    2
2    3
3    4
4    5
dtype: int64